# This should be filled out and placed in /cu-blogs/config/database.yml
# This file is *only* used to generate wp-config.php
production:
  host: 
  database: 
  username: 
  password:
staging:
  host: localhost
  database: chappress_dev
  username: chappress
  password: chappress
local:
  host: 
  database: 
  username:
  password: 
test:
  host: 
  database: 
  username:
  password: 